<?php

/**
 * @file
 * Contains functions related to the module functionality and Drupal hooks.
 */

declare(strict_types=1);

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function imagefield_tokens_help(string $route_name, RouteMatchInterface $route_match): ?string {
  switch ($route_name) {
    // Main module help for the image_field_tokens module.
    case 'help.page.image_field_tokens':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      return $output . ('<p>' . t('The ImageField Tokens module extends
      the default functionality of Image Widget and Formatter and adding
      the ability to specify default values and use content entity tokens
      in the Alt and Title text.') . '</p>');

    default:
  }
  return NULL;
}

/**
 * Implements hook_filefield_sources_widgets().
 *
 * This returns a list of widgets that are compatible with FileField Sources.
 */
function imagefield_tokens_filefield_sources_widgets(): array {
  return [
    'file_generic',
    'image_image',
    'imagefield_tokens',
    'imagefield_tokens_widget_crop',
  ];
}

/**
 * Implements hook_field_widget_info_alter().
 */
function imagefield_tokens_field_widget_info_alter(array &$info): void {
  // Disable ImageField Tokens crop widget if related module not installed.
  $module_handler = \Drupal::service('module_handler');
  if (!$module_handler->moduleExists('image_widget_crop')) {
    unset($info['imagefield_tokens_widget_crop']);
  }
}

/**
 * Implements hook_imce_supported_widgets_alter().
 *
 * If Imce module installed and enabled.
 * If Imce & ImageWidgetCrop modules both installed and enabled.
 */
function imagefield_tokens_imce_supported_widgets_alter(array &$widgets): void {
  $module_handler = \Drupal::service('module_handler');
  if ($module_handler->moduleExists('imce')) {
    $widgets[] = 'imagefield_tokens';
    if ($module_handler->moduleExists('image_widget_crop')) {
      $widgets[] = 'imagefield_tokens_widget_crop';
    }
  }
}

/**
 * Implements hook_field_formatter_info_alter().
 */
function imagefield_tokens_field_formatter_info_alter(array &$info): void {
  $module_handler = \Drupal::service('module_handler');
  if (!$module_handler->moduleExists('colorbox')) {
    unset($info['imagefield_tokens_colorbox']);
  }
}
